### ISSUE TITLE
Add request size cap to ConventionalDaemon

### ISSUE THREAD

**Issue by zpalmtree** [turtlecoin/turtlecoin-wallet-backend-js#1]
Same as we added to BlockchainCacheApi.

Don't have access to the request instance, so probably want to ditch turtlecoin-rpc and implement it ourselves.

**Comment by brandonlehmann** [comment]
Huh?

**Comment by zpalmtree** [comment]
This is my repo leave me alone :angry:

**Comment by brandonlehmann** [comment]
Fine!

**Comment by zpalmtree** [comment]
Not required anymore
