### ISSUE TITLE
deleteSubWallet not deleting publickSpendKey

### ISSUE THREAD

**Issue by Swepool** [turtlecoin/turtlecoin-wallet-backend-js#115]
If I create a subWallet and then delete it the publicSpendKey is still there so getBalance() tries to see balance from a non-existing wallet and throws an error.

**Comment by brandonlehmann** [comment]
Reviewed the code, I see where the issue exists.

**Comment by Swepool** [comment]
Here getBalance() checks all publicSpendKeys, so when running deleteSubWallet(address) the publicSpendKey of that address still persist in publicSpendKeys

```
            for (const publicSpendKey of publicSpendKeys) {
                const subWallet = this.subWallets.get(publicSpendKey);
                if (!subWallet) {
                    throw new Error('Subwallet not found!');
                }
                unconfirmedIncomingBalance += subWallet.getUnconfirmedChange();
            }
```

**Comment by Swepool** [comment]
And looks like you're not able to import same subwallet after deleting it

**Comment by Swepool** [comment]
Ok cool @brandonlehmann

**Comment by brandonlehmann** [comment]
> Ok cool @brandonlehmann

 Please try fixes on https://github.com/turtlecoin/turtlecoin-wallet-backend-js/tree/fixups-202205

**Comment by Swepool** [comment]
> > Ok cool @brandonlehmann
> 
> Please try fixes on https://github.com/turtlecoin/turtlecoin-wallet-backend-js/tree/fixups-202205

tyty, will do!

**Comment by Swepool** [comment]
Works now! @brandonlehmann 👍
