### ISSUE TITLE
Stuck in loop and slows the application down.

### ISSUE THREAD

**Issue by Swepool** [turtlecoin/turtlecoin-wallet-backend-js#116]
I think this loop is causing issues at times and slows the application significantly. 

https://github.com/turtlecoin/turtlecoin-wallet-backend-js/blob/master/lib/Transfer.ts#L979

`Attempting fee per byte transaction construction, attempt 469`

And it's basically running until restart.

**Comment by brandonlehmann** [comment]
This is as designed. If it’s looping forever, then you’ve got problems elsewhere as for it to loop forever, it’s has to **not** return and if you read the code and follow why it wouldn’t, then it’s problem outside the scope of this software.

**Comment by Swepool** [comment]
Hmm ok, I'll have to dig deeper then. Thanks bud.
