### ISSUE TITLE
support conventional daemon through SSL with turtlecoin-rpc

### ISSUE THREAD

**Issue by ExtraHash** [turtlecoin/turtlecoin-wallet-backend-js#26]
turtlecoin-rpc does support SSL, so we should be able to use a daemon over SSL with ConventionalDaemon()

**Comment by zpalmtree** [comment]
ConventionalDaemon and BlockchainCacheApi are both going to be depreciated by https://github.com/turtlecoin/turtlecoin-wallet-backend-js/issues/23 , so I am not going to add any features to them.
