### ISSUE TITLE
Uncaught Error: max-size on syncing

### ISSUE THREAD

**Issue by ExtraHash** [turtlecoin/turtlecoin-wallet-backend-js#28]
I'm getting an uncaught error on this after syncing for a while, I haven't figured out if it's at a specific block or just after a long time.

```
/home/ender/turtle-wallet-proton/node_modules/turtlecoin-wallet-backend/dist/lib/BlockchainCacheApi.js:325 Uncaught Error: max-size
    at Gunzip.res.body.on (/home/ender/turtle-wallet-proton/node_modules/turtlecoin-wallet-backend/dist/lib/BlockchainCacheApi.js:325)
    at Gunzip.emit (events.js:182)
    at addChunk (_stream_readable.js:283)
    at readableAddChunk (_stream_readable.js:264)
    at Gunzip.Readable.push (_stream_readable.js:219)
    at Gunzip.Transform.push (_stream_transform.js:151)
    at Zlib.processCallback (zlib.js:591)
```

[turtle-wallet-backend log](https://github.com/turtlecoin/turtlecoin-wallet-backend-js/files/3371262/protonwallet.log)

[Browser Console Log](https://github.com/turtlecoin/turtlecoin-wallet-backend-js/files/3371260/-1562648603865.log)

**Comment by ExtraHash** [comment]
got a bit more relevant wallet log, looks like it's block 208238 perhaps that's causing the issue
[wallet.log](https://github.com/turtlecoin/turtlecoin-wallet-backend-js/files/3371298/wallet.log)

**Comment by ExtraHash** [comment]
also looks like it does not effect ConventionalDaemon(), i have not tried the new Daemon() class to see if it fixes the problem or not yet

**Comment by zpalmtree** [comment]
It does fix it - this is because the chunk of blocks is too large for the specified max request size, so we throw that error, and should then catch it and retry with a smaller amount of blocks, but I removed the catch code.

I'll re-add it for now, didn't really want to touch the BlockchainCacheApi stuff cause it's a little complicated with all the abort stuff. I removed the abortcontroller stuff in the `Daemon()` class since it doesn't work in quite a few environments

**Comment by ExtraHash** [comment]
If the Daemon() constructor fixes the problem, I will just refactor the code to use it as I've been meaning to do that anyways.

**Comment by zpalmtree** [comment]
A bug is a bug, I'm fixing it now

**Comment by zpalmtree** [comment]
Actually... I didn't remove the catch handling.. not sure what's causing the error to not be caught

**Comment by zpalmtree** [comment]
I think this was probably an old issue caused by throwing an error in a `.on` callback function. It should be fixed now, but not 100% sure.

**Comment by ExtraHash** [comment]
that did fix my problem, thanks
