### ISSUE TITLE
fire event when daemon disconnects / refuses connection

### ISSUE THREAD

**Issue by ExtraHash** [turtlecoin/turtlecoin-wallet-backend-js#30]
Currently, if you try and connect to a daemon and it refuses the connection, the only way you can distinguish (that I've found) is that the network height will remain 0.  It would be useful if there was some event that fired if the daemon disconnects or refuses the connection / connection fails.

**Comment by zpalmtree** [comment]
I guess the best way to do this would be similar to the sync event.. just emit it if not already emitted on failing a request, and visa versa

**Comment by zpalmtree** [comment]
This is implemented in 3.4.3
