### ISSUE TITLE
rewind-to-height?

### ISSUE THREAD

**Issue by ExtraHash** [turtlecoin/turtlecoin-wallet-backend-js#32]
I think it would be fairly useful to allow a "rewind" option, basically it would function similar to a resync but instead of completely wiping the wallet of transactions and scanning again from block X, it would keep any transactions prior to block X and begin rescanning from that point

**Comment by zpalmtree** [comment]
Seems like a reasonable request.

**Comment by zpalmtree** [comment]
Implemented
