### ISSUE TITLE
transaction sometimes never confirms

### ISSUE THREAD

**Issue by ExtraHash** [turtlecoin/turtlecoin-wallet-backend-js#33]
This has happened to me quite a bit and also happened to rock as well, but if you send a transaction ~~to your own address,~~ it will occasionally never confirm and be stuck as unconfirmed. This requires a full rescan of the wallet to rectify. 

edit: i have just had this occur sending to an address other than the effected address. i've got an effected wallet file handy. here's the relevant output of getTransactions() for the effected transaction

```js
{ 
    blockHeight: 0,
    fee: 10,
    hash:
     '19adcd48d0e533c0ae0bb9c9e3774cc2e5a3d4cb60015dbaceb54e6817018a3b',
    isCoinbaseTransaction: false,
    paymentID:
     'd1f8f5f3c6e94c1162d6174884826731063f7b27e6c2b2ee7f83a328a3a592bd',
    timestamp: 0,
    transfers: {},
    unlockTime: 0 
}
```
As we can see from the block explorer, this transaction has several confirmations:
https://explorer.turtlecoin.lol/transaction.html?hash=19adcd48d0e533c0ae0bb9c9e3774cc2e5a3d4cb60015dbaceb54e6817018a3b

**Comment by zpalmtree** [comment]
Could you provide logging from before sending till after scanning has continued past the block it was included in, if possible?

**Comment by ExtraHash** [comment]
https://pastebin.com/dJL8RrKa

**Comment by ExtraHash** [comment]
just realized it didn't finish processing those last few blocks fired it back up and got the rest of it
[Mon, 22 Jul 2019 23:35:11 GMT] [Debug]: Zero blocks received from daemon, fully synced
[Mon, 22 Jul 2019 23:35:12 GMT] [Debug]: No blocks stored, fetching more.
[Mon, 22 Jul 2019 23:35:12 GMT] [Debug] [Daemon]: Updating daemon info...
[Mon, 22 Jul 2019 23:35:12 GMT] [Debug]: Zero blocks received from daemon, fully synced
[Mon, 22 Jul 2019 23:35:13 GMT] [Debug]: No blocks stored, fetching more.
[Mon, 22 Jul 2019 23:35:13 GMT] [Debug]: Zero blocks received from daemon, fully synced
[Mon, 22 Jul 2019 23:35:15 GMT] [Debug]: No blocks stored, fetching more.
[Mon, 22 Jul 2019 23:35:15 GMT] [Debug]: Zero blocks received from daemon, fully synced
[Mon, 22 Jul 2019 23:35:16 GMT] [Debug]: No blocks stored, fetching more.
[Mon, 22 Jul 2019 23:35:16 GMT] [Debug]: Zero blocks received from daemon, fully synced
[Mon, 22 Jul 2019 23:50:39 GMT] [Debug]: No blocks stored, fetching more.
[Mon, 22 Jul 2019 23:50:39 GMT] [Debug] [Daemon]: Updating daemon info...
[Mon, 22 Jul 2019 23:50:39 GMT] [Debug] [Sync] [Transactions]: Checking locked transactions...
[Mon, 22 Jul 2019 23:50:41 GMT] [Debug]: Processing block 1691076
[Mon, 22 Jul 2019 23:50:41 GMT] [Debug]: Finished processing block 1691076
[Mon, 22 Jul 2019 23:50:41 GMT] [Debug]: Processing block 1691081
[Mon, 22 Jul 2019 23:50:41 GMT] [Debug]: Finished processing block 1691081
[Mon, 22 Jul 2019 23:50:41 GMT] [Debug]: Processing block 1691084
[Mon, 22 Jul 2019 23:50:41 GMT] [Debug]: Finished processing block 1691084

**Comment by zpalmtree** [comment]
I don't see 073 in the logs which is the one the transaction was in.. 🤔

**Comment by ExtraHash** [comment]
you can see it was timing out which I think may be the issue

**Comment by zpalmtree** [comment]
Yeah, I saw that. Shouldn't effect the sync 'state' though.. will have to have another look

**Comment by ExtraHash** [comment]
from inspecting the log file further it appears it may just be skipping the block entirely once it resumes resyncing

**Comment by zpalmtree** [comment]
You have a copy of the wallet file?

**Comment by ExtraHash** [comment]
finally got a good log file of this occurring and then picking up the processing later

[zpalmlog.log](https://github.com/turtlecoin/turtlecoin-wallet-backend-js/files/3419558/zpalmlog.log)

let me PM you the wallet file

**Comment by ExtraHash** [comment]
I know that it was not expected this was fixed in 3.4.5 but I can confirm that this still happens in 3.4.5 and it just happened to me again, I have a log if you'd like

**Comment by zpalmtree** [comment]
Appears to be a bug in the cache API.

**Comment by brandonlehmann** [comment]
Not anymore (hopefully)
