### ISSUE TITLE
github install does not work

### ISSUE THREAD

**Issue by ExtraHash** [turtlecoin/turtlecoin-wallet-backend-js#36]
there's no compiled JS so i can't install the module via github

**Comment by zpalmtree** [comment]
Deal with it?

**Comment by RocksteadyTC** [comment]
come come now

**Comment by ExtraHash** [comment]
perhaps set up travis on this branch to auto-deploy to npm then?

**Comment by zpalmtree** [comment]
I don't want to auto deploy every commit I make

**Comment by ExtraHash** [comment]
if you're going to have features that are only available on GitHub, you should allow GitHub install. 

perhaps you could set up a second npm package for a "bleeding edge" release path that does deploys every commit, and leave the current one for "stable" releases.

**Comment by zpalmtree** [comment]
I make releases near instantly, if you need features quicker than that, then setup a build hook to compile the typescript yourself.

**Comment by brandonlehmann** [comment]
https://docs.npmjs.com/adding-dist-tags-to-packages
