### ISSUE TITLE
getBalance() returning incorrectly directly after a rewind() while still resyncing

### ISSUE THREAD

**Issue by ExtraHash** [turtlecoin/turtlecoin-wallet-backend-js#39]
Until the wallet is synced again, the balance is shown as incorrect. I have a stringified wallet in this state if you need to see one. It appears it may be incorrectly wiping the spentInputs array as it's not showing any spent inputs even though I did have outgoing transactions at this point in the history of the wallet.

**Comment by zpalmtree** [comment]
This is fixed now, right?

**Comment by ExtraHash** [comment]
yes sir

**Comment by ExtraHash** [comment]
I just had this happen again on a rewind(), it's setting getBalance() to 0 even though there would be a balance

**Comment by zpalmtree** [comment]
It's a deterministic process so if you can reproduce it once you should be able to repeat that. Do you think you might be able to get a copy of a wallet file so I can attempt to reproduce and fix it?

**Comment by ExtraHash** [comment]
yes, I can reproduce it every time using these steps:

1. open the wallet i'm about to send you
2. rewind to block 1700000
3. view the balance

**Comment by zpalmtree** [comment]
Issue was caused due to automatic input pruning of spent inputs older than 5000 blocks.
