### ISSUE TITLE
Transfer.js is returning ESOCKETIMEDOUT much faster than the 10,000 ms default

### ISSUE THREAD

**Issue by ExtraHash** [turtlecoin/turtlecoin-wallet-backend-js#46]
I'm trying to figure out why we're getting the "daemon not available/ frozen" error so often.

I logged the timeout error in Transfer.js and it's throwing an ESOCKETIMEDOUT as expected. However, it's throwing far quicker than ten seconds... the error message pops up almost as soon as sending the transaction.

**Comment by brandonlehmann** [comment]
Is this popping up for any other request types that you can see?

**Comment by zpalmtree** [comment]
Every request uses `makeRequest` <https://github.com/turtlecoin/turtlecoin-wallet-backend-js/blob/master/lib/Daemon.ts#L532> which sets the timeout here: <https://github.com/turtlecoin/turtlecoin-wallet-backend-js/blob/master/lib/Daemon.ts#L546> so I don't think it's a configuration issue. 

Possibly related? https://stackoverflow.com/a/37946324/8737306

**Comment by zpalmtree** [comment]
@ExtraHash Good to close now?

**Comment by ExtraHash** [comment]
Aye aye
