### ISSUE TITLE
"Something went wrong creating the transaction. Please try again"

### ISSUE THREAD

**Issue by ExtraHash** [turtlecoin/turtlecoin-wallet-backend-js#47]
I'm getting this error message on ~50% of transactions rn through my wallet. I'm not 100% sure what's going on, here are the logging steps i've taken...

I've added logging to verifyTransactionFee() to determine what is going on in this function. it seems to return true, so likely not the issue.

Looking at the code i'm not sure where else to log.

**Comment by zpalmtree** [comment]
Send with your own daemon, and observe the error message. For that matter, if you update to 4.0.0, the error message from the daemon should now be returned with this message.

**Comment by ExtraHash** [comment]
![image](https://user-images.githubusercontent.com/35851667/64560127-258ff780-d305-11e9-8236-468fac6f2259.png)

alright, here's the error message

however, I do not see how this is possible... I have been sending myself a transaction of the full balance over and over.

I resynced starting from the most recent transaction and tried again:

![image](https://user-images.githubusercontent.com/35851667/64560242-5f60fe00-d305-11e9-869d-f60e06a0b370.png)

**Comment by zpalmtree** [comment]
Did you install from github or npm?

**Comment by ExtraHash** [comment]
npm

**Comment by zpalmtree** [comment]
OK I have no idea then

**Comment by ExtraHash** [comment]
Ok, now I've just "received" the transaction I created, the one that presumably just returned the error message. for some reason it shows this as an incoming amount of the full balance of the transaction

![image](https://user-images.githubusercontent.com/35851667/64560812-85d36900-d306-11e9-8b2f-ff3a52d3a8b1.png)

**Comment by zpalmtree** [comment]
Sounds like it sent after all and this is https://github.com/turtlecoin/turtlecoin-wallet-backend-js/issues/31 ?
Shouldn't be seeing it as an incoming transaction tho.. sounds like the key images aren't being matched or something

**Comment by ExtraHash** [comment]
Yes, that's what it seems like as well. However the backend never registered it "sending" for whatever reason, and then as a result it goofed up when scanning the transaction

**Comment by zpalmtree** [comment]
The backend should not screw up regardless of it knowing if it sent the transaction or not - it's no different to syncing a wallet with outgoing transactions. Please enable trace logging and provide the output from before sending to after scanning the transaction.

**Comment by ExtraHash** [comment]
[Mon, 09 Sep 2019 20:19:45 GMT] [Debug] [Transactions]: Generated key images for 0 inputs, used pre-generated key images for 8 inputs.

this was printed to the console using 4.0.0 and getting this error

**Comment by zpalmtree** [comment]
This is not an error

**Comment by ExtraHash** [comment]
I believe this is rectified with the latest cache update.
