### ISSUE TITLE
seems to be getting stuck on specific blocks

### ISSUE THREAD

**Issue by ExtraHash** [turtlecoin/turtlecoin-wallet-backend-js#49]
here's a log example

https://pastebin.com/hepJ1SJB

went on like this for a few minutes before it finally went on to the next block

**Comment by zpalmtree** [comment]
This appears to be the cache returning duplicate data. Both line 24 and line 34 are returning block `1833860`.

**Comment by ExtraHash** [comment]
ok

**Comment by brandonlehmann** [comment]
> ok

*cough* fixed *cough*
