### ISSUE TITLE
autooptimize doesn't seem to be optimizing

### ISSUE THREAD

**Issue by ExtraHash** [turtlecoin/turtlecoin-wallet-backend-js#50]
for example, here is a transaction i just attempted to send

```[Wed, 11 Sep 2019 02:22:27 GMT] [Trace] [Daemon]: Making request to /randomOutputs with params {"amounts":[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,90,90,90,90,90,90,90,90,90,90,90,90,90,90,90,90,100,100,300,300,500,500,500,600,700,700,700,700,700,700,800,800,800,800,800,800,800,800,800,800,800,800,800,900,900,900,900,900,900,900,900,900,900,900,900,900,900,900,900,900,900,900,900,900,900,900,900,900,900,900,900,900,900,900,900,900,900,900,900,900,900,900,7000,7000,7000,7000,7000,8000,8000,8000,8000,8000,8000,8000,8000,8000,8000,8000,8000,8000,8000,9000,9000,9000,9000,9000,9000,9000,9000,9000,9000,9000,9000,9000,9000,9000,9000,9000,9000,9000,9000,9000,60000,70000,70000,70000,80000,80000,80000,80000,80000,80000,80000,80000,80000,80000,90000,90000,90000,90000,90000,90000,90000,90000,500000,700000,700000,800000,800000,900000,900000,900000,900000,5000000,7000000,7000000,40000000],"mixin":4}```

**Comment by zpalmtree** [comment]
Try now.

**Comment by brandonlehmann** [comment]
Now I know what transaction to look for as his. Thanks @ExtraHash

**Comment by ExtraHash** [comment]
OK, seems to be fixed with that latest
