### ISSUE TITLE
validatePaymentID() returns SUCCESS on empty string

### ISSUE THREAD

**Issue by ExtraHash** [turtlecoin/turtlecoin-wallet-backend-js#55]
I don't believe  it should validate this

**Comment by zpalmtree** [comment]
You're not exactly wrong, but to be honest these are internal library functions that I thought might be helpful for others, so I exposed them.

I just use them to verify that there's a valid payment ID, or no payment ID.
How about I add a bool parameter to determine if empty payment ID's are considered valid?

**Comment by ExtraHash** [comment]
that would probably be just fine, it doesn't cause me any headache with how it currently validates an empty string but I could see it being an issue in some implementations

**Comment by zpalmtree** [comment]
Resolved in https://github.com/turtlecoin/turtlecoin-wallet-backend-js/pull/57
