### ISSUE TITLE
Iincomingtx event question

### ISSUE THREAD

**Issue by n8tb1t** [turtlecoin/turtlecoin-wallet-backend-js#63]
Is it possible to get the receiving wallet address in the `incomingtx` event? once the transaction received I want to know where it belongs.

**Comment by zpalmtree** [comment]
Not really, as it could be going to multiple receiving wallet addresses. You can map each `transfers` public key to the corresponding subwallet - it is somewhat cumbersome to do, however..

```js
wallet.on('incomingtx', (transaction) => {
    const publicKeyToAddressMap = new Map();

    for (const address of wallet.getAddresses()) {
        publicKeyToAddressMap.set(wallet.getPublicSpendKeys(address)[0], address);
    }

    for (const [publicKey, amount] of this.transfers) {
        console.log(`Address ${publicKeyToAddressMap.get(publicKey)} received transfer of ${WB.prettyPrintAmount(amount)}`);
    }
});
```

I can make a helper function to go from a public key to an address, if that helps.

**Comment by n8tb1t** [comment]
Thank you very much! I can take it from here.
The only thing is not clear to me how the transaction can go to multiple receiving wallet addresses?
`wallet.on('incomingtx'` loop from individual transactions? so if we have multiple transactions on same block it will be triggered multiple times, so each transaction will belong to only one subwallet?>

**Comment by n8tb1t** [comment]
well, I think I got it, so the transaction can have multiple transfers, though, but the code you provided solving the issue so it will be easy to update DB and UI:)

**Comment by zpalmtree** [comment]
Yep, a single transaction can have multiple transfers, if you send to multiple destinations, for example, a pool paying everyone who helped mine a block in one transaction.

**Comment by n8tb1t** [comment]
Thanks! this package is amazing, it's saving so much time!
