### ISSUE TITLE
Slow sync

### ISSUE THREAD

**Issue by n8tb1t** [turtlecoin/turtlecoin-wallet-backend-js#64]
It takes like a couple of seconds(3-20) to process each block on the local daemon, is there a way to speed it up?

**Comment by ExtraHash** [comment]
The sync speed depends on the environment you're running the code in, are you using this in a browser or where are you running the backend

**Comment by zpalmtree** [comment]
Also, try syncing from zero, and see if the speed is still slow. There are some very heavy blocks at the top of the chain which is likely causing slowdowns.

**Comment by n8tb1t** [comment]
@zpalmtree I'm running it on pure `nodejs` - on 16 core I7 CPU with 64GB ram, created the new wallet yesterday, and I only need to sync like 1K block from the last launch. It's extremely slow and uses a lot of CPU. Shouldn't it be almost instant with local daemon! How syncing from 0 is going to help?

**Comment by zpalmtree** [comment]
It's not going to help, but it should demonstrate that the issue is only with the latest blocks. There's a ton of transactions with many thousands of outputs which is very non-typical, and the time to process a block is linear based on the number of outputs - in an empty (coinbase only) block, there's only about 7 or so outputs to process.

**Comment by zpalmtree** [comment]
Testing with zedwallet-beta, it appears to be the bottleneck is on fetching data from the daemon. The threaded-rpc PR should be able to help with this, along with another plan I have for making data transfer quicker. You might see the same if you up your log level - I don't imagine it's much different for the backend than zedwallet-beta.

**Comment by n8tb1t** [comment]
Thank you, you where right, some heavy blocks, past them, and the sync is going extremally fast!:)))
But I noticed that on these heavy blocks the other threads in the app become unresponsive like something was locking them... what could it be? the backend-js is running in the async function.

**Comment by zpalmtree** [comment]
Node is single threaded unfortunately, so one function running for a *looong* time with no callbacks / async etc to allow other sections of the code to run will indeed cause your app to lag. 

The blocksPerTick https://turtlecoin.github.io/turtlecoin-wallet-backend-js/interfaces/_config_.iconfig.html#blockspertick value can help configure how many blocks we sync before yielding to other threads, I thought this was 100 by default but seems it's already set to 1, so won't really help with this issue.

@ExtraHash might be able to advise on how you can use a web worker or something to run the sync process on another thread, I'm not too familiar with any of those packages.

**Comment by n8tb1t** [comment]
Do you have compiled windows bins for `https://github.com/turtlecoin/turtlecoin/pull/903` ? I would've compiled it myself, but don't have the build tools on this machine :(

**Comment by n8tb1t** [comment]
LOL I just rebuilt the turtlecoin-crypto package for my platform with GYP, and after that, it synced 1K blocks in like 5 seconds. so this was the problem!

**Comment by zpalmtree** [comment]
Nice! Can you expand on why it didn't work originally for you? Would be good to fix for future users if it's something on my end :)

**Comment by n8tb1t** [comment]
well, because compiling the `turtlecoin-crypto` is optional during the package installation, so it was running some unoptimized multiplatform version of `turtlecoin-crypto` package. In order for it to compile on Windows, you'll need Python and Visual Studio Build Tools installed. You can just recommend using compiled `turtlecoin-crypto` package, on Linux it's done automatically, and on windows requires some preinstalled software! https://github.com/nodejs/node-gyp#on-windows

**Comment by zpalmtree** [comment]
Thanks! I'll update the readme to mention this somewhere.

**Comment by brandonlehmann** [comment]
FYI :)

![image](https://user-images.githubusercontent.com/20562132/69558335-04d75580-0f76-11ea-8612-6fc491d2ba26.png)


I'm also experimenting with prebuilds for the turtlecoin-crypto package which would skip the compilation on most platforms.
