### ISSUE TITLE
Intresting issue

### ISSUE THREAD

**Issue by n8tb1t** [turtlecoin/turtlecoin-wallet-backend-js#66]
I've:
- created a new wallet
- imported sub wallet from another wallet with `PrivateSpendKey`
- tried to resync the whole wallet.

but it doesn't find incoming transactions to the imported sub wallet. Is it a normal behavior?

**Comment by zpalmtree** [comment]
>imported sub wallet from another wallet with PrivateSpendKey
From another wallet? Subwallets need to have the same, shared private view key, so you can't import an unrelated wallet.
