### ISSUE TITLE
ERROR: Could not Base58 decode supplied address

### ISSUE THREAD

**Issue by n8tb1t** [turtlecoin/turtlecoin-wallet-backend-js#69]
```js
  const [hash, error] = await this.wallet.sendTransactionAdvanced(
      [[withdrawRequest.to, withdrawRequest.amount]],
      undefined,
      1000,
      undefined,
      [withdrawRequest.from]
    );
```

throws 
```
(node:8736) UnhandledPromiseRejectionWarning: Error: Could not Base58 decode supplied address. Please check the length and try again.: TypeError: Cannot read property 'length' of undefined
```
and  `hash` is not returned, but the transaction is executed so I receive the coins on the other end.
What could be the problem?

**Comment by n8tb1t** [comment]
now I get `WalletError { errorCode: 11, customMessage: '' }`

**Comment by zpalmtree** [comment]
I can't seem to reproduce this. I tested with the following code:
```js
const [hash, err] = await wallet.sendTransactionAdvanced(
    [['TRTLv2Fyavy8CXG8BPEbNeCHFZ1fuDCYCZ3vW5H5LXN4K2M2MHUpTENip9bbavpHvvPwb4NDkBWrNgURAd5DB38FHXWZyoBh4wW', 1]],
    undefined,
    10,
    'c59d157d1d96f280ece0816a8925cae8232432b7235d1fa92c70faf3064434b2',
    ['TRTLuzkmaW7F8S6JFytJwpVUBXFYLJDKPR8kBxbe8vbH1V8Ho1Jw2zbW1nFpNSnCzYBASjdfBMJFh8rJhfQiGt54biz32YcCAPW']
);
```

I tested with 1 subwallet in the wallet, multiple, sending to the primary address as change, sending to another subwallet as change, sending to a subwallet as the destination, all succeeded. 

Can you post the parameters of `withdrawRequest.to`, `withdrawRequest.amount`, and `withdrawRequest.from`, and can you provide your `Config` argument if you're passing one when you construct the wallet instance?

> now I get `WalletError { errorCode: 11, customMessage: '' }`

That error is `Not Enough Balance`. Are you calling `.toString()` on the error? It should give you the actual error message for future reference.

**Comment by n8tb1t** [comment]
Ok seams, that the balance from the sub wallet returned to the main address. I'll test it more and let you know how it goes! thanks. Probably I just missed something
