### ISSUE TITLE
Previously downloaded cache style blocks are treated as non cache blocks after swapping node

### ISSUE THREAD

**Issue by ExtraHash** [turtlecoin/turtlecoin-wallet-backend-js#72]
[wallet-backend.log](https://github.com/turtlecoin/turtlecoin-wallet-backend-js/files/3981874/wallet-backend.log)

log file attached. on line 762 you can see where i switch from 10.0.0.12:11898 to node.trtlpay.com:80

on line 895 it begins erroring on the blocks:

```
[Thu, 19 Dec 2019 05:36:14 GMT] [Info]: Error processing blocks: Error: This call is not supported on the cache api. The cache API returns global indexes directly from /getWalletSyncData
```

**Comment by zpalmtree** [comment]
Looks like it downloaded blocks from the conventional daemon, which were missing global indexes, then tried to retrieve global indexes later for these blocks after having swapped to a blockchain cache which doesn't support this call

Probably have to discard stored blocks upon swapping node.

**Comment by zpalmtree** [comment]
I believe 94290052c9c37fe427848c428492bc82cb4283f2 should have fixed this. Please let me know if you can reproduce the issue with this commit applied.

**Comment by ExtraHash** [comment]
I *believe* this is fixed, however, i can't build up any more than 25 blocks in memory at a time at the moment with the cache due to #76 so it's a little difficult to test

**Comment by zpalmtree** [comment]
Will leave open for now then

**Comment by ExtraHash** [comment]
I can confirm this is fixed
