### ISSUE TITLE
Previously non coinbase blocks downloaded are attempted to be processed after enabling scanning coinbase transactions

### ISSUE THREAD

**Issue by ExtraHash** [turtlecoin/turtlecoin-wallet-backend-js#73]
[type-error.log](https://github.com/turtlecoin/turtlecoin-wallet-backend-js/files/3981966/type-error.log)

some  strange behavior going on here. the sync appeared to be skipping some blocks entirely, and eventually errorred out on line 1858. Killing the backend process and restarting it resumed syncing as normal (no typeerror, no skipped blocks)

**Comment by zpalmtree** [comment]
After reviewing the possible lines we could get this error, the only place I could imagine this could occur is either here: <https://github.com/turtlecoin/turtlecoin-wallet-backend-js/blob/master/lib/WalletSynchronizer.ts#L651>

or here: <https://github.com/turtlecoin/turtlecoin-wallet-backend-js/blob/master/lib/WalletSynchronizer.ts#L688>

The former could potentially occur if a block without a coinbase transaction was downloaded, then scanning coinbase transactions was flipped on. The second, I can't imagine occurring unless somehow the transactions aren't present on the block object.

I think I'll need to see trace logs to be able to fix this if you are able to reproduce. In addition, would be great if you could get the exact line that is thrown from, might be possible via dev tools / debugging.

**Comment by ExtraHash** [comment]
I did flip on coinbase scanning to see if it would stop skipping blocks, so that's the almost definite cause then. Should setting coinbase scanning also clear stored blocks then?

**Comment by zpalmtree** [comment]
Probably yes

**Comment by zpalmtree** [comment]
I believe this should be resolved by e7a8498. Please give it a try and report back.

**Comment by ExtraHash** [comment]
this does appear to be fixed

**Comment by zpalmtree** [comment]
Great.
