### ISSUE TITLE
getNodeFee() returns 0 immediately after calling wallet.start()

### ISSUE THREAD

**Issue by ExtraHash** [turtlecoin/turtlecoin-wallet-backend-js#75]
It seems like it takes a bit of time for the feeAmount to return correctly; i'm getting 0 when I return it directly after calling wallet.start(). it would be useful if there was some kind of ready event to let me know when I could pull the value

it seems once the wallet actually starts syncing, then the function returns the correct amount, i was able to work around this like follows:

```ts
  async getNodeFee(): void {
    await sleep(1000);
    this.wallet.getNodeFee()[1] // returns correctly
  }
```

**Comment by zpalmtree** [comment]
Cannot reproduce. Please ensure you are awaiting `start()`.

https://repl.it/repls/ConventionalWateryQuerylanguage
