### ISSUE TITLE
long delay between fetching blocks and processing them

### ISSUE THREAD

**Issue by ExtraHash** [turtlecoin/turtlecoin-wallet-backend-js#76]
![image](https://user-images.githubusercontent.com/35851667/71490767-e15c3080-27e9-11ea-9c49-6d7abfb00cbe.png)

I'm getting this behavior specifically from the cache; note the long delay between successfully fetching the blocks and beginning to process them. Unsure what is causing this

**Comment by zpalmtree** [comment]
Try removing this line https://github.com/turtlecoin/turtlecoin-wallet-backend-js/blob/master/lib/WalletBackend.ts#L2244

**Comment by ExtraHash** [comment]
removing that line seems to resolve the issue

**Comment by zpalmtree** [comment]
Ok, I will review how better to limit when we are having issues collecting blocks.

**Comment by zpalmtree** [comment]
I decided to just disable the sleeping for now. This will mean that the event loop will run with reckless abandon even when you have no internet connection or whatever, which could *potentially* slow down your app. I couldn't think of a simple way to implement sleeps without hurting performance.

Please open a new issue if you have problems with this change.
