### ISSUE TITLE
outgoing transaction no longer immediately appearing in wallet.getTransactions()

### ISSUE THREAD

**Issue by ExtraHash** [turtlecoin/turtlecoin-wallet-backend-js#77]
Previously, as soon as I had sent a transaction, I could call `wallet.getTransactions()` and it would be present in the transaction array. This appears to no longer be the case: the outgoing transaction does not appear in the transaction array until it has actually been included in a block. This hurts the UX imo: users want to be sure that the transaction worked, so it's better to show the transaction immediately.

**Comment by zpalmtree** [comment]
This was not intended and I'm not sure what could cause it, `storeSentTransaction` should handle that. Will review.

**Comment by ExtraHash** [comment]
Not sure if it helps but it also does not fire the outgoingtx event until it's included in a block either

**Comment by zpalmtree** [comment]
> Not sure if it helps but it also does not fire the outgoingtx event until it's included in a block either

That is expected behaviour

**Comment by zpalmtree** [comment]
Can you provide a full `DEBUG` log of you sending a transaction, then calling `getTransactions()`? I can't see how this could occur.

**Comment by ExtraHash** [comment]
Ok, give me a bit here

**Comment by zpalmtree** [comment]
If possible, run the latest commit, it has slightly improved logging that will help demonstrate the ordering of the function calls.

**Comment by ExtraHash** [comment]
it appears i was calling the wrong function in my backend process, so it just wasn't getting sent over the wire like I thought it was 🤦‍♀️
