### ISSUE TITLE
More prepared transactions functions

### ISSUE THREAD

**Issue by zpalmtree** [turtlecoin/turtlecoin-wallet-backend-js#83]
One to remove all prepared transactions and one to list all prepared transactions

**Comment by wannnz10** [comment]
Halo

**Comment by brandonlehmann** [comment]
> Halo

Harro

**Comment by ivantse** [comment]
Seems like both removal and listing are already implemented:
* [deletePreparedTransactions](https://github.com/turtlecoin/turtlecoin-wallet-backend-js/blob/master/lib/WalletBackend.ts#L2760)
* [getPreparedTransactions](https://github.com/turtlecoin/turtlecoin-wallet-backend-js/blob/master/lib/WalletBackend.ts#L2779)

Is there anything else for this issue? Happy to take a crack at it if there's more.

**Comment by zpalmtree** [comment]
I think this is completed, yeah.
